import type {
  ActionRequest,
  AutoModeSettings,
  CaseDetail,
  CaseSummary,
  DataSourceSummary,
  DetectorDefinition,
  ImpactOverview,
  LiveWorkItem,
  OrganizationSummary,
  SlaExtractionBatch,
  SlaRulebookEntry,
} from "../../domain/business-sentry";

export function mockOrg(orgId: number): OrganizationSummary {
  return {
    id: orgId,
    name: "Demo Enterprise",
    industry: "Manufacturing",
    geography: "IN",
  };
}

export const MOCK_CASES: CaseSummary[] = [
  {
    id: "case-1001",
    organization_id: 1,
    module: "procure_watch",
    title: "Duplicate invoice pattern — TechSource",
    summary: "Three invoices share the same PO line within 48h.",
    case_type: "invoice_anomaly",
    severity: "critical",
    status: "open",
    team: "AP North",
    vendor: "TechSource",
    detector_name: "DupInvoiceWindow",
    owner_name: "R. Iyer",
    approver_name: "M. Kapoor",
    projected_impact: 125000,
    realized_impact: 0,
    approval_state: "pending",
    action_state: "blocked",
    sla_countdown_minutes: 180,
    sla_risk_level: "high",
    recommended_action_label: "Hold payment + vendor query",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-28T14:30:00Z",
  },
  {
    id: "case-2002",
    organization_id: 1,
    module: "sla_sentinel",
    title: "P1 queue — predicted breach",
    summary: "Ticket volume spike; response SLA at risk.",
    case_type: "sla_risk",
    severity: "high",
    status: "in_progress",
    team: "Support East",
    vendor: "N/A",
    detector_name: "QueueBacklogSLA",
    owner_name: "A. Sen",
    approver_name: "VP Support",
    projected_impact: 90000,
    realized_impact: 0,
    approval_state: "approved",
    action_state: "ready",
    sla_countdown_minutes: 45,
    sla_risk_level: "critical",
    recommended_action_label: "Reassign + exec notification",
    created_at: "2026-03-27T08:00:00Z",
    updated_at: "2026-03-29T09:00:00Z",
  },
  {
    id: "case-3003",
    organization_id: 1,
    module: "procure_watch",
    title: "Billed rate above contract — CloudCorp",
    summary: "Unit rate 12% over catalog for SKU CC-API-01.",
    case_type: "vendor_rate",
    severity: "medium",
    status: "open",
    team: "Vendor Mgmt",
    vendor: "CloudCorp",
    detector_name: "ContractRateDelta",
    owner_name: "S. Patel",
    approver_name: "M. Kapoor",
    projected_impact: 48000,
    realized_impact: 12000,
    approval_state: "approved",
    action_state: "executed",
    sla_countdown_minutes: null,
    sla_risk_level: "low",
    recommended_action_label: "Credit memo request",
    created_at: "2026-03-15T12:00:00Z",
    updated_at: "2026-03-25T16:00:00Z",
  },
  {
    id: "case-4004",
    organization_id: 1,
    module: "procure_watch",
    title: "PO–invoice–payment mismatch",
    summary: "Three-way match failure on PO-8891.",
    case_type: "reconciliation",
    severity: "medium",
    status: "open",
    team: "AP North",
    vendor: "LogiFreight",
    detector_name: "ThreeWayMatch",
    owner_name: "R. Iyer",
    approver_name: "C. Nair",
    projected_impact: 22000,
    realized_impact: 0,
    approval_state: "rejected",
    action_state: "blocked",
    sla_countdown_minutes: 600,
    sla_risk_level: "medium",
    recommended_action_label: "Manual reconciliation",
    created_at: "2026-03-10T09:00:00Z",
    updated_at: "2026-03-22T11:00:00Z",
  },
];

export const MOCK_CASE_DETAILS: Record<string, CaseDetail> = {
  "case-1001": {
    summary: MOCK_CASES[0]!,
    why_flagged:
      "Invoices INV-9921, INV-9924, INV-9927 match amount and PO line within sliding 48h window.",
    root_cause: "Likely duplicate submission after ERP retry; vendor portal shows single shipment.",
    baseline_comparison: "Historical duplicate rate for vendor: 0.2% vs current week 4.1%.",
    evidence: [
      {
        id: "ev-1",
        kind: "invoice",
        label: "INV-9921",
        snippet: "Amount ₹41,200 — PO PO-7788 line 3",
      },
      {
        id: "ev-2",
        kind: "invoice",
        label: "INV-9924",
        snippet: "Amount ₹41,200 — PO PO-7788 line 3",
      },
    ],
    related_entities: [
      { type: "vendor", id: "v-12", name: "TechSource" },
      { type: "po", id: "po-7788", name: "PO-7788" },
    ],
    sla: {
      name: "AP dispute resolution",
      response_deadline: "2026-03-29T09:00:00Z",
      resolution_deadline: "2026-03-31T18:00:00Z",
      penalty_if_breach: 25000,
    },
    financial_impact: { amount: 125000, currency: "INR", confidence: 0.78 },
    formula: "sum(duplicate_candidates.amount) - confirmed_payments",
    recommended_action: { label: "Hold payment + vendor query", playbook_id: "ap-hold-01" },
    approval_chain: [{ step: 1, role: "AP Lead", name: "M. Kapoor", state: "pending" }],
    timeline: [
      { at: "2026-03-20T10:00:00Z", event: "Detector fired", actor: "system" },
      { at: "2026-03-20T10:02:00Z", event: "Case opened", actor: "system" },
      { at: "2026-03-21T08:00:00Z", event: "Assigned to R. Iyer", actor: "workflow" },
    ],
  },
  "case-2002": {
    summary: MOCK_CASES[1]!,
    why_flagged: "P1 backlog exceeded threshold; predicted response SLA miss.",
    root_cause: "Two agents out sick; unassigned queue growth.",
    baseline_comparison: "Normal P1 backlog: 4 tickets; current: 19.",
    evidence: [{ id: "ev-s1", kind: "ticket", label: "INC-44102", snippet: "P1 · unassigned 2h" }],
    related_entities: [{ type: "team", id: "t-7", name: "Support East" }],
    sla: {
      name: "Enterprise P1",
      response_deadline: "2026-03-29T16:00:00Z",
      resolution_deadline: "2026-03-30T09:00:00Z",
      penalty_if_breach: 90000,
    },
    financial_impact: { amount: 90000, currency: "INR", confidence: 0.65 },
    formula: "projected_penalty_if_breach",
    recommended_action: { label: "Reassign + exec notification", playbook_id: "sla-esc-01" },
    approval_chain: [
      { step: 1, role: "VP Support", name: "VP Support", state: "approved" },
    ],
    timeline: [{ at: "2026-03-27T08:00:00Z", event: "SLA risk escalated", actor: "SLA Sentinel" }],
  },
};

function defaultCaseDetail(c: CaseSummary): CaseDetail {
  return {
    summary: { ...c, organization_id: c.organization_id },
    why_flagged: "Flagged by detector rules for this workspace.",
    root_cause: "Under investigation.",
    baseline_comparison: "Baseline comparison not yet computed.",
    evidence: [],
    related_entities: [],
    sla: null,
    financial_impact: { amount: c.projected_impact, currency: "INR", confidence: 0.6 },
    formula: "projected_impact from detector metadata",
    recommended_action: { label: c.recommended_action_label },
    approval_chain: [{ step: 1, role: "Approver", name: c.approver_name, state: c.approval_state }],
    timeline: [{ at: c.created_at, event: "Case created", actor: "system" }],
  };
}

export function getMockCaseDetail(caseId: string): CaseDetail | null {
  const known = MOCK_CASE_DETAILS[caseId];
  if (known) return known;
  const summary = MOCK_CASES.find((c) => c.id === caseId);
  if (!summary) return null;
  return defaultCaseDetail(summary);
}

export function mockImpact(orgId: number): ImpactOverview {
  return {
    organization: mockOrg(orgId),
    metrics: [
      { label: "Money at risk (30d)", value: 3200000, delta: 12 },
      { label: "Open cases", value: 94, delta: null },
      { label: "SLA breaches avoided (YTD)", value: 38, delta: 5 },
    ],
    top_vendors_by_risk: [
      { vendor: "CloudCorp", risk_score: 0.92, projected_impact: 480000 },
      { vendor: "TechSource", risk_score: 0.88, projected_impact: 125000 },
      { vendor: "LogiFreight", risk_score: 0.71, projected_impact: 22000 },
    ],
    top_teams_by_overload: [
      { team: "Support East", open_items: 38, sla_breach_risk: "high" },
      { team: "AP North", open_items: 24, sla_breach_risk: "medium" },
      { team: "Vendor Mgmt", open_items: 11, sla_breach_risk: "low" },
    ],
    realized_vs_projected: {
      periods: ["W1", "W2", "W3", "W4"],
      realized_savings: [120000, 145000, 98000, 210000],
      projected_savings: [200000, 220000, 180000, 260000],
    },
    recent_cases: MOCK_CASES.slice(0, 3),
    approval_execution_funnel: {
      pending_approval: 12,
      approved: 8,
      rejected: 2,
      executed: 15,
    },
  };
}

export const MOCK_LIVE_OPS: LiveWorkItem[] = [
  {
    id: "lo-501",
    item_type: "sla_response",
    title: "P1 ticket queue — breach in 3h",
    team: "Support East",
    owner_name: "A. Sen",
    status: "in_progress",
    current_stage: "response",
    assigned_sla_name: "Enterprise P1",
    response_deadline: "2026-03-29T16:00:00Z",
    resolution_deadline: "2026-03-30T09:00:00Z",
    time_remaining_minutes: 175,
    predicted_breach_risk: "high",
    projected_penalty: 90000,
    projected_business_impact: 120000,
    linked_case_id: "case-2002",
    suggested_action: "Reassign + exec notification",
    match_rationale: ["Matched rule Enterprise P1 on module support", "Time remaining below response SLA window"],
    workflow_category: "support",
  },
  {
    id: "lo-502",
    item_type: "approval_wait",
    title: "Payment hold pending AP lead",
    team: "AP North",
    owner_name: "R. Iyer",
    status: "waiting",
    current_stage: "approval",
    assigned_sla_name: "AP dispute resolution",
    response_deadline: "2026-03-29T09:00:00Z",
    resolution_deadline: "2026-03-31T18:00:00Z",
    time_remaining_minutes: 320,
    predicted_breach_risk: "medium",
    projected_penalty: 25000,
    projected_business_impact: 40000,
    linked_case_id: "case-1001",
    suggested_action: "Nudge approver M. Kapoor",
    match_rationale: ["Queue depth within policy; approval gate is the bottleneck"],
    workflow_category: "procure",
  },
];

export const MOCK_DATA_SOURCES: DataSourceSummary[] = [
  {
    id: "ds-1",
    connector_id: 1,
    name: "SAP AP export",
    schema: "public",
    qualified_name: "public.sap_ap_export",
    source_type: "csv_upload",
    status: "healthy",
    freshness_status: "current",
    last_synced_at: "2026-03-28T06:00:00Z",
    record_count: 128400,
    schema_preview: ["invoice_id", "vendor_id", "amount", "posted_at"],
    health: "ok",
    upload_history: [{ at: "2026-03-28T06:00:00Z", filename: "ap_mar28.csv", rows: 4200 }],
    size_bytes: 0,
    preview_row_count: 20,
  },
  {
    id: "ds-2",
    connector_id: 1,
    name: "Contract PDFs",
    schema: "public",
    qualified_name: "public.contract_pdfs",
    source_type: "document",
    status: "degraded",
    freshness_status: "stale",
    last_synced_at: "2026-03-20T06:00:00Z",
    record_count: 42,
    schema_preview: ["document_id", "vendor", "effective_date"],
    health: "warning",
    upload_history: [{ at: "2026-03-20T06:00:00Z", filename: "msa_bundle.zip", rows: 42 }],
    size_bytes: 0,
    preview_row_count: 5,
  },
];

export const MOCK_DETECTORS: DetectorDefinition[] = [
  {
    id: "det-01",
    name: "DupInvoiceWindow",
    description: "Flags duplicate invoice candidates on same PO line within 48h.",
    module: "procure_watch",
    business_domain: "accounts_payable",
    severity: "high",
    owner_name: "Finance Ops",
    enabled: true,
    logic_type: "sql_rule",
    logic_summary: "Windowed join on vendor + amount + PO line.",
    query_logic: "SELECT i.* FROM invoices i ...",
    expected_output_fields: ["invoice_id", "po_id", "amount"],
    linked_action_template: "Hold payment + vendor query",
    linked_cost_formula: "sum(candidate.amount)",
    schedule_minutes: 60,
    generation_source: "manual",
    validation_status: "validated",
    last_triggered_at: "2026-03-28T02:00:00Z",
    last_run_at: "2026-03-28T02:00:00Z",
    next_run_at: "2026-03-28T03:00:00Z",
    issue_count: 14,
  },
  {
    id: "det-02",
    name: "QueueBacklogSLA",
    description: "Predicts SLA breach from queue depth and arrival rate.",
    module: "sla_sentinel",
    business_domain: "customer_support",
    severity: "critical",
    owner_name: "Support Ops",
    enabled: true,
    logic_type: "threshold",
    logic_summary: "If P1_unassigned > 10 and trend > 0 → risk.",
    query_logic: "metrics: queue_depth, arrival_rate",
    expected_output_fields: ["team", "predicted_breach_risk"],
    linked_action_template: "Reassign + exec notification",
    linked_cost_formula: "projected_penalty_if_breach",
    schedule_minutes: 60,
    generation_source: "manual",
    validation_status: "validated",
    last_triggered_at: "2026-03-29T01:00:00Z",
    last_run_at: "2026-03-29T01:00:00Z",
    next_run_at: "2026-03-29T02:00:00Z",
    issue_count: 6,
  },
  {
    id: "det-03",
    name: "ContractRateDelta",
    description: "Compares billed unit rate to contract catalog.",
    module: "procure_watch",
    business_domain: "vendor_management",
    severity: "medium",
    owner_name: "Vendor Mgmt",
    enabled: false,
    logic_type: "sql_rule",
    logic_summary: "Join invoice lines to contract SKU table.",
    query_logic: "SELECT ... billed_rate, contract_rate ...",
    expected_output_fields: ["invoice_line_id", "delta_pct"],
    linked_action_template: "Credit memo request",
    linked_cost_formula: "sum(overcharge_amount)",
    schedule_minutes: 60,
    generation_source: "manual",
    validation_status: "validated",
    last_triggered_at: "2026-03-25T18:00:00Z",
    last_run_at: "2026-03-25T18:00:00Z",
    next_run_at: "2026-03-25T19:00:00Z",
    issue_count: 3,
  },
];

export const MOCK_SLA_RULES: SlaRulebookEntry[] = [
  {
    id: "sla-rule-1",
    name: "Enterprise P1",
    status: "active",
    applies_to: "Priority 1 incidents",
    applies_to_payload: { label: "Priority 1 incidents", module: "support" },
    conditions: "severity = P1 AND customer_tier = enterprise",
    response_deadline_hours: 2,
    resolution_deadline_hours: 24,
    penalty_amount: 90000,
    escalation_owner: "VP Support",
    business_hours_logic: "24x7",
    auto_action_allowed: false,
    source_document_name: "MSA-2024.pdf",
    last_reviewed_at: "2026-01-15T00:00:00Z",
    rule_version: 1,
  },
  {
    id: "sla-rule-2",
    name: "AP dispute",
    status: "active",
    applies_to: "Invoice disputes",
    applies_to_payload: { label: "Invoice disputes", module: "procure_watch" },
    conditions: "amount > ₹50,000",
    response_deadline_hours: 24,
    resolution_deadline_hours: 120,
    penalty_amount: 25000,
    escalation_owner: "Controller",
    business_hours_logic: "business_hours_IST",
    auto_action_allowed: false,
    source_document_name: "Finance_Policy.pdf",
    last_reviewed_at: "2025-11-01T00:00:00Z",
    rule_version: 1,
  },
];

export const MOCK_SLA_BATCHES: SlaExtractionBatch[] = [
  {
    id: "1",
    source_document_name: "Vendor_SLA_draft.pdf",
    document_type: "pdf",
    status: "pending_review",
    uploaded_at: "2026-03-27T11:00:00Z",
    extraction_source: "mock_seed",
    run_metadata: { engine: "stub", version: "1" },
    candidate_rules: [
      {
        id: 101,
        name: "Response time 4h",
        conditions: "All vendor tickets",
        response_deadline_hours: 4,
        resolution_deadline_hours: 48,
        penalty_amount: 10000,
        status: "pending_review",
        confidence_score: 0.82,
        parsing_notes: ["Detected explicit 4h response clause"],
        extraction_source: "mock_seed",
      },
      {
        id: 102,
        name: "Resolution 5 business days",
        conditions: "Material defects",
        response_deadline_hours: 8,
        resolution_deadline_hours: 40,
        penalty_amount: 5000,
        status: "pending_review",
        confidence_score: 0.71,
        parsing_notes: [],
        extraction_source: "mock_seed",
      },
    ],
  },
];

export const MOCK_ACTIONS_SEED: ActionRequest[] = [
  {
    id: "act-501",
    case_id: "case-1001",
    title: "Hold payment batch #448",
    recommended_next_step: "Notify vendor with evidence pack",
    rationale: "Duplicate pattern exceeds threshold; avoid double pay.",
    expected_savings: 125000,
    avoided_loss: 0,
    risk_level: "medium",
    required_approver: "M. Kapoor",
    evidence_pack_summary: ["3 invoices", "PO-7788", "timeline"],
    approval_state: "pending",
    execution_state: "not_started",
    created_at: "2026-03-28T09:00:00Z",
    updated_at: "2026-03-28T09:00:00Z",
    recommendation_id: "9001",
    alert_title: "Dup cluster · TechSource · AP North · 3× @ 125,000 · FIN-001, FIN-002",
    alert_type: "duplicate_spend",
    action_type: "hold_payment_batch",
  },
  {
    id: "act-502",
    case_id: "case-2002",
    title: "Surge staffing — Support East",
    recommended_next_step: "Approve temp shift coverage",
    rationale: "Reduce breach probability below 40%.",
    expected_savings: 40000,
    avoided_loss: 90000,
    risk_level: "high",
    required_approver: "VP Support",
    evidence_pack_summary: ["Queue metrics", "forecast"],
    approval_state: "approved",
    execution_state: "ready",
    created_at: "2026-03-27T10:00:00Z",
    updated_at: "2026-03-28T08:00:00Z",
    recommendation_id: "9002",
    alert_title: "SLA risk · support ticket · Enterprise P1 · workflow 12",
    alert_type: "sla_risk",
    action_type: "reroute_queue",
  },
  {
    id: "act-503",
    case_id: "case-4004",
    title: "Close PO-8891 reconciliation task",
    recommended_next_step: "Reject — await vendor revised invoice",
    rationale: "Mismatch explained by partial shipment.",
    expected_savings: 0,
    avoided_loss: 0,
    risk_level: "low",
    required_approver: "C. Nair",
    evidence_pack_summary: ["GRN vs invoice lines"],
    approval_state: "rejected",
    execution_state: "not_started",
    created_at: "2026-03-21T09:00:00Z",
    updated_at: "2026-03-22T11:00:00Z",
    recommendation_id: "9003",
    alert_title: "Units mismatch · INV-PO-8891-A",
    alert_type: "vendor_discrepancy",
    action_type: "open_review_task",
  },
  {
    id: "act-504",
    case_id: "case-3003",
    title: "Credit memo — CloudCorp SKU drift",
    recommended_next_step: "Mark complete in ERP",
    rationale: "Vendor issued CM-992.",
    expected_savings: 48000,
    avoided_loss: 12000,
    risk_level: "low",
    required_approver: "M. Kapoor",
    evidence_pack_summary: ["CM-992 attached"],
    approval_state: "approved",
    execution_state: "executed",
    created_at: "2026-03-18T09:00:00Z",
    updated_at: "2026-03-25T16:00:00Z",
    recommendation_id: "9004",
    alert_title: "Rate over contract · CC-INV-2044",
    alert_type: "rate_mismatch",
    action_type: "notify_vendor",
  },
];

export const MOCK_AUTO_MODE: AutoModeSettings = {
  organization_id: 1,
  policies: [
    {
      id: 1,
      name: "Low-risk procure holds",
      module: "procure_watch",
      scope: "low_risk_procure",
      risk_level: "low",
      enabled: false,
      approver_name: "M. Kapoor",
      allowed_actions: ["hold_payment_batch", "notify_vendor"],
      condition_summary: "Duplicate invoice pattern under ₹25k with matched GRN",
      expires_at: null,
    },
    {
      id: 2,
      name: "Support surge auto-staffing",
      module: "ops_resilience",
      scope: "support_east",
      risk_level: "medium",
      enabled: false,
      approver_name: "VP Support",
      allowed_actions: ["temp_shift_coverage"],
      condition_summary: "Queue depth > 2× baseline for 4+ hours",
      expires_at: null,
    },
  ],
};
