import type {
  ActionRequest,
  AutoModeSettings,
  CaseDetail,
  DataSourceSummary,
  DatasetPreview,
  DatasetSummary,
  ImpactOverview,
  LiveWorkItem,
  SavedAnomalyQuery,
  SlaExtractionBatch,
  SlaRulebookEntry,
  SourceAgentMemory,
} from "../domain/business-sentry";
import type { InvestigationResult } from "../types/api";

export type DemoSourceCard = DataSourceSummary & {
  dimensions: string[];
};

export type DemoQueryRun = {
  label: string;
  sql: string;
  note: string;
};

export type DemoCopilotScenario = {
  summary: string;
  reasoning: string[];
  actions: DemoQueryRun[];
  result: InvestigationResult;
};

export const demoSourceCards: DemoSourceCard[] = [
  {
    id: "orders",
    name: "Orders fact",
    source_type: "postgres_table",
    status: "connected",
    freshness_status: "6 min ago",
    last_synced_at: "2026-03-29T18:42:00+05:30",
    record_count: 149811,
    schema_preview: ["order_id", "store_id", "city_id", "promised_eta_min", "delivered_at", "basket_value"],
    health: "healthy",
    upload_history: [{ at: "2026-03-29T18:36:00+05:30", filename: "orders_sync_2026_03_29", rows: 149811 }],
    dimensions: ["14 days", "34 dark stores", "6 cities"],
  },
  {
    id: "delivery_events",
    name: "Delivery events",
    source_type: "postgres_table",
    status: "connected",
    freshness_status: "6 min ago",
    last_synced_at: "2026-03-29T18:42:00+05:30",
    record_count: 1198488,
    schema_preview: ["event_id", "order_id", "event_type", "event_ts", "driver_id", "minutes_from_order"],
    health: "healthy",
    upload_history: [{ at: "2026-03-29T18:36:00+05:30", filename: "delivery_events_sync_2026_03_29", rows: 1198488 }],
    dimensions: ["8 lifecycle stages", "858 drivers", "15 min median ETA"],
  },
  {
    id: "inventory_snapshots",
    name: "Inventory + capacity snapshots",
    source_type: "postgres_table",
    status: "connected",
    freshness_status: "12 min ago",
    last_synced_at: "2026-03-29T18:36:00+05:30",
    record_count: 8160,
    schema_preview: ["snapshot_date", "store_id", "picker_utilization_pct", "dispatch_bay_utilization_pct", "cold_storage_utilization_pct"],
    health: "healthy",
    upload_history: [{ at: "2026-03-29T18:30:00+05:30", filename: "inventory_snapshots_sync_2026_03_29", rows: 8160 }],
    dimensions: ["240 store-days", "7 resource classes", "capacity + utilization"],
  },
  {
    id: "invoices",
    name: "Vendor invoices",
    source_type: "postgres_table",
    status: "warning",
    freshness_status: "2 hr ago",
    last_synced_at: "2026-03-29T16:51:00+05:30",
    record_count: 354,
    schema_preview: ["invoice_id", "vendor_id", "contract_id", "billed_units", "contracted_rate", "invoice_amount"],
    health: "degraded",
    upload_history: [{ at: "2026-03-29T16:51:00+05:30", filename: "vendor_invoice_drop_mar29", rows: 354 }],
    dimensions: ["26 vendors", "5 contract families", "INR billing"],
  },
  {
    id: "work_items",
    name: "Ops work items",
    source_type: "postgres_table",
    status: "connected",
    freshness_status: "8 min ago",
    last_synced_at: "2026-03-29T18:40:00+05:30",
    record_count: 1102,
    schema_preview: ["work_item_id", "store_id", "category", "status", "sla_deadline_at", "assigned_team"],
    health: "healthy",
    upload_history: [{ at: "2026-03-29T18:34:00+05:30", filename: "ops_queue_sync_2026_03_29", rows: 1102 }],
    dimensions: ["5 workflow categories", "14 approvers", "110 active escalations"],
  },
  {
    id: "employees_drivers",
    name: "People graph",
    source_type: "postgres_table",
    status: "connected",
    freshness_status: "18 min ago",
    last_synced_at: "2026-03-29T18:30:00+05:30",
    record_count: 1917,
    schema_preview: ["entity_id", "entity_type", "store_id", "team_id", "manager_id", "capacity_band"],
    health: "healthy",
    upload_history: [{ at: "2026-03-29T18:30:00+05:30", filename: "resource_graph_sync_2026_03_29", rows: 1917 }],
    dimensions: ["1,059 employees", "858 drivers", "12 operating teams"],
  },
];

export const demoDatasets: DatasetSummary[] = [
  { id: "orders", name: "orders", record_count: 149811, columns: ["order_id", "store_id", "city_id", "promised_eta_min", "delivered_at", "basket_value"], source_uri: "demo://delivra/orders", schema: "synthetic_demo" },
  { id: "delivery_events", name: "delivery_events", record_count: 1198488, columns: ["event_id", "order_id", "event_type", "event_ts", "driver_id", "minutes_from_order"], source_uri: "demo://delivra/delivery_events", schema: "synthetic_demo" },
  { id: "inventory_snapshots", name: "inventory_snapshots", record_count: 8160, columns: ["snapshot_date", "store_id", "picker_utilization_pct", "dispatch_bay_utilization_pct", "cold_storage_utilization_pct"], source_uri: "demo://delivra/inventory_snapshots", schema: "synthetic_demo" },
  { id: "invoices", name: "invoices", record_count: 354, columns: ["invoice_id", "vendor_id", "contract_id", "billed_units", "contracted_rate", "invoice_amount"], source_uri: "demo://delivra/invoices", schema: "synthetic_demo" },
  { id: "work_items", name: "work_items", record_count: 1102, columns: ["work_item_id", "store_id", "category", "status", "sla_deadline_at", "assigned_team"], source_uri: "demo://delivra/work_items", schema: "synthetic_demo" },
];

export const demoDatasetPreviews: Record<string, DatasetPreview> = {
  orders: {
    id: "orders",
    name: "orders",
    schema: "synthetic_demo",
    source_uri: "demo://delivra/orders",
    row_count: 149811,
    columns: ["order_id", "store_id", "city_id", "promised_eta_min", "delivered_at", "basket_value", "driver_id"],
    rows: [
      { order_id: "ORD-BLR-102918", store_id: "BLR-HSR-04", city_id: "BLR", promised_eta_min: 12, delivered_at: "2026-03-29 18:31", basket_value: 624, driver_id: "DRV-182" },
      { order_id: "ORD-GGN-094215", store_id: "GGN-SEC54-02", city_id: "GGN", promised_eta_min: 10, delivered_at: "2026-03-29 18:27", basket_value: 418, driver_id: "DRV-047" },
      { order_id: "ORD-MUM-221084", store_id: "MUM-AND-01", city_id: "MUM", promised_eta_min: 14, delivered_at: "2026-03-29 18:43", basket_value: 871, driver_id: "DRV-501" },
      { order_id: "ORD-HYD-132809", store_id: "HYD-KPHB-03", city_id: "HYD", promised_eta_min: 9, delivered_at: "2026-03-29 18:22", basket_value: 352, driver_id: "DRV-633" },
    ],
  },
  delivery_events: {
    id: "delivery_events",
    name: "delivery_events",
    schema: "synthetic_demo",
    source_uri: "demo://delivra/delivery_events",
    row_count: 1198488,
    columns: ["event_id", "order_id", "event_type", "event_ts", "driver_id", "minutes_from_order"],
    rows: [
      { event_id: "EVT-900221", order_id: "ORD-BLR-102918", event_type: "picker_assigned", event_ts: "2026-03-29 18:08", driver_id: null, minutes_from_order: 1 },
      { event_id: "EVT-900222", order_id: "ORD-BLR-102918", event_type: "packed", event_ts: "2026-03-29 18:14", driver_id: null, minutes_from_order: 7 },
      { event_id: "EVT-900223", order_id: "ORD-BLR-102918", event_type: "driver_picked_up", event_ts: "2026-03-29 18:19", driver_id: "DRV-182", minutes_from_order: 12 },
      { event_id: "EVT-900224", order_id: "ORD-BLR-102918", event_type: "delivered", event_ts: "2026-03-29 18:31", driver_id: "DRV-182", minutes_from_order: 24 },
    ],
  },
  inventory_snapshots: {
    id: "inventory_snapshots",
    name: "inventory_snapshots",
    schema: "synthetic_demo",
    source_uri: "demo://delivra/inventory_snapshots",
    row_count: 8160,
    columns: ["snapshot_date", "store_id", "picker_utilization_pct", "dispatch_bay_utilization_pct", "cold_storage_utilization_pct", "idle_driver_minutes"],
    rows: [
      { snapshot_date: "2026-03-29", store_id: "BLR-HSR-04", picker_utilization_pct: 91, dispatch_bay_utilization_pct: 96, cold_storage_utilization_pct: 84, idle_driver_minutes: 42 },
      { snapshot_date: "2026-03-29", store_id: "GGN-SEC54-02", picker_utilization_pct: 88, dispatch_bay_utilization_pct: 93, cold_storage_utilization_pct: 79, idle_driver_minutes: 35 },
      { snapshot_date: "2026-03-29", store_id: "MUM-AND-01", picker_utilization_pct: 97, dispatch_bay_utilization_pct: 98, cold_storage_utilization_pct: 90, idle_driver_minutes: 12 },
      { snapshot_date: "2026-03-29", store_id: "HYD-KPHB-03", picker_utilization_pct: 83, dispatch_bay_utilization_pct: 86, cold_storage_utilization_pct: 72, idle_driver_minutes: 58 },
    ],
  },
  invoices: {
    id: "invoices",
    name: "invoices",
    schema: "synthetic_demo",
    source_uri: "demo://delivra/invoices",
    row_count: 354,
    columns: ["invoice_id", "vendor_id", "contract_id", "billed_units", "contracted_rate", "invoice_amount", "variance_pct"],
    rows: [
      { invoice_id: "INV-FLT-202603-118", vendor_id: "V-LASTMILE-03", contract_id: "CTR-LM-03", billed_units: 81240, contracted_rate: 14.2, invoice_amount: 1299840, variance_pct: 12.6 },
      { invoice_id: "INV-PPG-202603-044", vendor_id: "V-PACK-02", contract_id: "CTR-PKG-02", billed_units: 285000, contracted_rate: 1.7, invoice_amount: 542000, variance_pct: 11.8 },
      { invoice_id: "INV-CLD-202603-019", vendor_id: "V-COLD-01", contract_id: "CTR-COLD-01", billed_units: 188, contracted_rate: 2200, invoice_amount: 472800, variance_pct: 14.3 },
      { invoice_id: "INV-STS-202603-009", vendor_id: "V-STAFF-01", contract_id: "CTR-STF-01", billed_units: 920, contracted_rate: 1180, invoice_amount: 1113200, variance_pct: 8.9 },
    ],
  },
  work_items: {
    id: "work_items",
    name: "work_items",
    schema: "synthetic_demo",
    source_uri: "demo://delivra/work_items",
    row_count: 1102,
    columns: ["work_item_id", "store_id", "category", "status", "sla_deadline_at", "assigned_team", "risk_band"],
    rows: [
      { work_item_id: "WI-OPS-1022", store_id: "BLR-HSR-04", category: "late_delivery_cluster", status: "open", sla_deadline_at: "2026-03-29 19:00", assigned_team: "Regional Fleet Control", risk_band: "critical" },
      { work_item_id: "WI-OPS-1049", store_id: "MUM-AND-01", category: "cold_chain_breach", status: "open", sla_deadline_at: "2026-03-29 19:15", assigned_team: "Cold Chain Operations", risk_band: "high" },
      { work_item_id: "WI-OPS-1074", store_id: "GGN-SEC54-02", category: "driver_shortfall", status: "open", sla_deadline_at: "2026-03-29 19:24", assigned_team: "Last Mile Scheduling", risk_band: "high" },
      { work_item_id: "WI-OPS-1082", store_id: "HYD-KPHB-03", category: "picker_queue_spike", status: "open", sla_deadline_at: "2026-03-29 19:32", assigned_team: "Dark Store Operations", risk_band: "medium" },
    ],
  },
};

export const demoSourceMemory: SourceAgentMemory = {
  id: 1,
  status: "ready",
  engine_name: "Gemini + LangChain SQL planner",
  summary_text:
    "Connected source looks like a quick-commerce operating warehouse. Core fact tables cover orders, invoice controls, delivery events, inventory capacity, and SLA-linked work items. Most joins route through store_id, order_id, vendor_id, contract_id, and team_id. High-signal anomaly surfaces are vendor overbilling, delivery breach clusters, dispatch bottlenecks, and idle labor pockets.",
  dashboard_brief:
    "Recommended dashboard blocks: top anomaly leakage by detector, city/store breach map, vendor variance ranking, overloaded teams, and saved actions awaiting approval. Emphasize Bengaluru HSR, Mumbai Andheri, and Gurgaon Sector 54 because they have the strongest combined financial and SLA risk signals in the current slice.",
  schema_notes:
    "Dark stores represent warehouse-like fulfillment nodes. Drivers are modeled as resources. Team routing should prioritize Regional Fleet Control, Dark Store Operations, Procurement Controls, and Finance AP Audit.",
  memory_path: "/memory/delivra_india_snapshot.json",
  context_snapshot: {},
  created_at: "2026-03-29T18:42:00+05:30",
  updated_at: "2026-03-29T18:42:00+05:30",
};

export const demoAnomalyQueries: SavedAnomalyQuery[] = [
  {
    id: 1,
    name: "Contract rate drift on vendor invoices",
    description: "Flags invoices where billed effective rate drifts more than 8% above contract for repeated cycles.",
    category: "procurewatch",
    enabled: true,
    created_at: "2026-03-29T18:20:00+05:30",
    sql_text:
      "select vendor_id, contract_id, sum(invoice_amount - billed_units * contracted_rate) as leakage_inr from invoices where variance_pct > 8 group by 1,2 having count(*) >= 2 order by leakage_inr desc limit 10;",
  },
  {
    id: 2,
    name: "Late delivery cluster around dispatch bay saturation",
    description: "Links delivery delay bursts to stores running near dispatch bay capacity and low active-driver coverage.",
    category: "sla_sentinel",
    enabled: true,
    created_at: "2026-03-29T18:22:00+05:30",
    sql_text:
      "select o.store_id, count(*) as delayed_orders, avg(i.dispatch_bay_utilization_pct) as bay_util, avg(i.idle_driver_minutes) as idle_driver_min from orders o join inventory_snapshots i on o.store_id = i.store_id and date(o.delivered_at) = i.snapshot_date where o.delivered_at is not null and extract(epoch from (o.delivered_at - o.created_at))/60 > o.promised_eta_min + 8 group by 1 having count(*) >= 20 order by delayed_orders desc;",
  },
  {
    id: 3,
    name: "Cold-chain SLA breach candidates",
    description: "Surfaces work items where response and resolution windows are likely to miss based on queue age and current ownership.",
    category: "sla_sentinel",
    enabled: true,
    created_at: "2026-03-29T18:24:00+05:30",
    sql_text:
      "select store_id, category, count(*) as open_cases, min(sla_deadline_at) as nearest_deadline from work_items where status = 'open' and category in ('cold_chain_breach','late_delivery_cluster') group by 1,2 order by nearest_deadline asc;",
  },
  {
    id: 4,
    name: "Idle rider pockets during demand trough",
    description: "Identifies stores carrying excess rider minutes relative to order density and dispatch volume.",
    category: "resource_optimization",
    enabled: true,
    created_at: "2026-03-29T18:26:00+05:30",
    sql_text:
      "select store_id, avg(idle_driver_minutes) as avg_idle_driver_min, avg(dispatch_bay_utilization_pct) as bay_util from inventory_snapshots group by 1 having avg(idle_driver_minutes) > 45 and avg(dispatch_bay_utilization_pct) < 82 order by avg_idle_driver_min desc;",
  },
];

export const demoImpactOverview: ImpactOverview = {
  organization: {
    id: 101,
    name: "Delivra India",
    industry: "Quick commerce",
    geography: "India",
  },
  metrics: [
    { label: "Projected leakage", value: 4180000, delta: null },
    { label: "SLA penalty exposure", value: 1360000, delta: null },
    { label: "Open critical anomalies", value: 14, delta: null },
    { label: "Approved actions", value: 23, delta: null },
  ],
  top_vendors_by_risk: [
    { vendor: "RapidFleet Logistics", risk_score: 0.93, projected_impact: 1180000 },
    { vendor: "PolarNest Cold Chain", risk_score: 0.88, projected_impact: 790000 },
    { vendor: "PackRight Consumables", risk_score: 0.74, projected_impact: 540000 },
    { vendor: "ShiftStack Staffing", risk_score: 0.63, projected_impact: 420000 },
  ],
  top_teams_by_overload: [
    { team: "Regional Fleet Control", open_items: 18, sla_breach_risk: "high" },
    { team: "Dark Store Operations", open_items: 14, sla_breach_risk: "high" },
    { team: "Cold Chain Operations", open_items: 9, sla_breach_risk: "medium" },
    { team: "Finance AP Audit", open_items: 7, sla_breach_risk: "medium" },
  ],
  realized_vs_projected: {
    periods: ["Mar 24", "Mar 25", "Mar 26", "Mar 27", "Mar 28", "Mar 29"],
    realized_savings: [220000, 250000, 310000, 360000, 410000, 480000],
    projected_savings: [420000, 460000, 510000, 590000, 620000, 710000],
    capture_rate_pct: 61.3,
  },
  approval_execution_funnel: {
    pending_approval: 7,
    approved: 23,
    rejected: 3,
    executed: 18,
  },
  recent_cases: [
    {
      id: "CASE-INV-118",
      organization_id: 101,
      module: "procurewatch",
      title: "RapidFleet invoice billed 12.6% above contract",
      summary: "Repeated rate drift across Bengaluru and Gurgaon lanes over the last two invoice cycles.",
      case_type: "invoice_variance",
      severity: "critical",
      status: "open",
      team: "Finance AP Audit",
      vendor: "RapidFleet Logistics",
      detector_name: "Contract rate drift on vendor invoices",
      owner_name: "Ananya Shah",
      approver_name: "Rohit Menon",
      projected_impact: 684000,
      realized_impact: 0,
      approval_state: "pending",
      action_state: "drafted",
      sla_countdown_minutes: 180,
      sla_risk_level: "medium",
      recommended_action_label: "Hold disputed line items and request vendor credit note",
      created_at: "2026-03-29T15:20:00+05:30",
      updated_at: "2026-03-29T18:20:00+05:30",
    },
    {
      id: "CASE-SLA-442",
      organization_id: 101,
      module: "sla_sentinel",
      title: "Bengaluru HSR late-delivery cluster near dispatch saturation",
      summary: "54 orders breached promise window after dispatch bays hit 96% utilization during the evening spike.",
      case_type: "delivery_breach_cluster",
      severity: "critical",
      status: "investigating",
      team: "Regional Fleet Control",
      vendor: "Internal fleet",
      detector_name: "Late delivery cluster around dispatch bay saturation",
      owner_name: "Siddharth Rao",
      approver_name: "Pooja Nair",
      projected_impact: 452000,
      realized_impact: 0,
      approval_state: "approved",
      action_state: "queued",
      sla_countdown_minutes: 43,
      sla_risk_level: "critical",
      recommended_action_label: "Rebalance riders from nearby stores and cap slot density",
      created_at: "2026-03-29T17:08:00+05:30",
      updated_at: "2026-03-29T18:28:00+05:30",
    },
    {
      id: "CASE-RES-211",
      organization_id: 101,
      module: "procurewatch",
      title: "Hyderabad KPHB rider idle pocket during low dispatch window",
      summary: "Store carried 58 average idle rider minutes despite subdued order density and low bay usage.",
      case_type: "resource_idle",
      severity: "high",
      status: "open",
      team: "Last Mile Scheduling",
      vendor: "Internal fleet",
      detector_name: "Idle rider pockets during demand trough",
      owner_name: "Megha Iyer",
      approver_name: "Sandeep Kulkarni",
      projected_impact: 194000,
      realized_impact: 0,
      approval_state: "pending",
      action_state: "drafted",
      sla_countdown_minutes: 540,
      sla_risk_level: "low",
      recommended_action_label: "Shift riders to evening flex pool and compress low-density shifts",
      created_at: "2026-03-29T14:12:00+05:30",
      updated_at: "2026-03-29T18:11:00+05:30",
    },
  ],
};

export const demoAnomalyHits = [
  {
    queryId: 1,
    title: "RapidFleet and PolarNest show repeated contract-rate drift",
    triggeredCases: 6,
    impactInr: 980000,
    owner: "Finance AP Audit",
  },
  {
    queryId: 2,
    title: "Bengaluru HSR and Mumbai Andheri have delay clusters tied to bay saturation",
    triggeredCases: 9,
    impactInr: 820000,
    owner: "Regional Fleet Control",
  },
  {
    queryId: 3,
    title: "Cold-chain queues are on track to miss escalation windows in Mumbai and Gurgaon",
    triggeredCases: 4,
    impactInr: 610000,
    owner: "Cold Chain Operations",
  },
  {
    queryId: 4,
    title: "Idle rider capacity is concentrated in Hyderabad KPHB and Noida Sector 76",
    triggeredCases: 7,
    impactInr: 280000,
    owner: "Last Mile Scheduling",
  },
];

export const demoCases: ImpactOverview["recent_cases"] = [
  ...demoImpactOverview.recent_cases,
  {
    id: "CASE-SLA-517",
    organization_id: 101,
    module: "sla_sentinel",
    title: "PolarNest reefer downtime threatens chilled-order SLA",
    summary: "Cold-chain exceptions are stacking up in Mumbai Andheri after reefer utilization crossed 90%.",
    case_type: "cold_chain_breach",
    severity: "high",
    status: "investigating",
    team: "Cold Chain Operations",
    vendor: "PolarNest Cold Chain",
    detector_name: "Cold-chain SLA breach candidates",
    owner_name: "Pooja Nair",
    approver_name: "Ishita Bansal",
    projected_impact: 318000,
    realized_impact: 0,
    approval_state: "pending",
    action_state: "drafted",
    sla_countdown_minutes: 68,
    sla_risk_level: "high",
    recommended_action_label: "Escalate reefer downtime and reroute chilled orders",
    created_at: "2026-03-29T16:38:00+05:30",
    updated_at: "2026-03-29T18:17:00+05:30",
  },
  {
    id: "CASE-INV-204",
    organization_id: 101,
    module: "procurewatch",
    title: "PackRight packaging invoice exceeds usage baseline",
    summary: "Packaging spend spiked despite stable order volume in Gurgaon and Noida.",
    case_type: "usage_mismatch",
    severity: "medium",
    status: "open",
    team: "Procurement Controls",
    vendor: "PackRight Consumables",
    detector_name: "Contract rate drift on vendor invoices",
    owner_name: "Nikita Verma",
    approver_name: "Rohit Menon",
    projected_impact: 162000,
    realized_impact: 0,
    approval_state: "pending",
    action_state: "drafted",
    sla_countdown_minutes: 720,
    sla_risk_level: "low",
    recommended_action_label: "Validate billed usage against dispatch counts",
    created_at: "2026-03-29T13:21:00+05:30",
    updated_at: "2026-03-29T17:42:00+05:30",
  },
  {
    id: "CASE-OPS-305",
    organization_id: 101,
    module: "sla_sentinel",
    title: "Gurgaon Sector 54 driver shortfall building escalation queue",
    summary: "Driver acceptance dipped below target and the open exception queue is growing into the next slot.",
    case_type: "driver_shortfall",
    severity: "high",
    status: "open",
    team: "Regional Fleet Control",
    vendor: "Internal fleet",
    detector_name: "Late delivery cluster around dispatch bay saturation",
    owner_name: "Arjun Khanna",
    approver_name: "Pooja Nair",
    projected_impact: 141000,
    realized_impact: 0,
    approval_state: "approved",
    action_state: "queued",
    sla_countdown_minutes: 52,
    sla_risk_level: "high",
    recommended_action_label: "Trigger standby rider pool and shrink slot density",
    created_at: "2026-03-29T17:02:00+05:30",
    updated_at: "2026-03-29T18:29:00+05:30",
  },
];

export const demoCaseDetails: Record<string, CaseDetail> = {
  "CASE-INV-118": {
    summary: demoCases[0],
    why_flagged: "RapidFleet billed two consecutive cycles above contract by more than the configured 8% variance threshold.",
    root_cause: "Lane-level invoicing picked up a surcharge not present in the signed contract schedule.",
    baseline_comparison: "Current effective rate is 12.6% above 6-week trailing contract baseline.",
    evidence: [
      { id: "ev-1", kind: "invoice", label: "Invoice INV-FLT-202603-118", snippet: "Billed amount 1,299,840 INR vs contracted expectation 1,154,000 INR." },
      { id: "ev-2", kind: "contract", label: "Contract CTR-LM-03", snippet: "Last-mile lane pricing fixed at 14.2 INR per billed unit for this cycle." },
    ],
    related_entities: [
      { type: "vendor", id: "V-LASTMILE-03", name: "RapidFleet Logistics" },
      { type: "team", id: "TEAM-FIN-01", name: "Finance AP Audit" },
    ],
    sla: {
      name: "Vendor dispute response",
      response_deadline: "2026-03-29T20:45:00+05:30",
      resolution_deadline: "2026-03-31T18:00:00+05:30",
      penalty_if_breach: 180000,
    },
    financial_impact: { amount: 684000, currency: "INR", confidence: 0.91 },
    formula: "sum(invoice_amount - billed_units * contracted_rate) across flagged lanes",
    recommended_action: { label: "Hold disputed line items and request vendor credit note", playbook_id: "ap_dispute_hold_v2" },
    approval_chain: [
      { step: 1, role: "Finance AP Lead", name: "Rohit Menon", state: "pending" },
      { step: 2, role: "Procurement Head", name: "Aditi Kapoor", state: "queued" },
    ],
    timeline: [
      { at: "2026-03-29T15:20:00+05:30", event: "Detector triggered", actor: "Contract rate drift on vendor invoices" },
      { at: "2026-03-29T16:02:00+05:30", event: "Leakage estimate computed", actor: "SLA.ck" },
      { at: "2026-03-29T18:20:00+05:30", event: "Approval packet drafted", actor: "Ananya Shah" },
    ],
  },
  "CASE-SLA-442": {
    summary: demoCases[1],
    why_flagged: "Late deliveries stacked above the promise buffer while dispatch bay utilization held near peak capacity.",
    root_cause: "Bengaluru HSR hit a dispatch bottleneck during the evening spike; rider supply alone would not clear the queue.",
    baseline_comparison: "Store delay rate rose to 18.4% versus a 6.1% four-week baseline.",
    evidence: [
      { id: "ev-3", kind: "ops", label: "Store/day performance", snippet: "54 orders breached promise window with average dispatch bay utilization at 96%." },
      { id: "ev-4", kind: "workflow", label: "Work item WI-OPS-1022", snippet: "Late-delivery cluster escalated to Regional Fleet Control with 43 minutes left on SLA." },
    ],
    related_entities: [
      { type: "store", id: "BLR-HSR-04", name: "Bengaluru HSR 04" },
      { type: "team", id: "TEAM-FLEET-01", name: "Regional Fleet Control" },
    ],
    sla: {
      name: "Customer delivery recovery",
      response_deadline: "2026-03-29T19:08:00+05:30",
      resolution_deadline: "2026-03-29T20:00:00+05:30",
      penalty_if_breach: 220000,
    },
    financial_impact: { amount: 452000, currency: "INR", confidence: 0.88 },
    formula: "delayed_orders * avg_refund_per_order + projected_retention_loss",
    recommended_action: { label: "Rebalance riders from nearby stores and cap slot density", playbook_id: "fleet_rebalance_urgent" },
    approval_chain: [
      { step: 1, role: "Regional Ops Manager", name: "Pooja Nair", state: "approved" },
      { step: 2, role: "City Ops Lead", name: "Siddharth Rao", state: "executing" },
    ],
    timeline: [
      { at: "2026-03-29T17:08:00+05:30", event: "Delay cluster opened", actor: "SLA Sentinel" },
      { at: "2026-03-29T17:46:00+05:30", event: "Dispatch saturation confirmed", actor: "SLA.ck" },
      { at: "2026-03-29T18:28:00+05:30", event: "Rebalance plan approved", actor: "Pooja Nair" },
    ],
  },
  "CASE-RES-211": {
    summary: demoCases[2],
    why_flagged: "Idle rider minutes stayed high while dispatch utilization remained low over multiple snapshot windows.",
    root_cause: "Scheduling is carrying too much fixed rider coverage through low-density afternoon demand.",
    baseline_comparison: "Idle minutes at 58 versus network median of 24 for stores in the same demand band.",
    evidence: [
      { id: "ev-5", kind: "resource", label: "Inventory snapshot", snippet: "Average idle driver minutes 58 with dispatch bay utilization at 72%." },
      { id: "ev-6", kind: "orders", label: "Order density", snippet: "Afternoon order volume 31% below similar Hyderabad stores." },
    ],
    related_entities: [
      { type: "store", id: "HYD-KPHB-03", name: "Hyderabad KPHB 03" },
      { type: "team", id: "TEAM-FLEET-02", name: "Last Mile Scheduling" },
    ],
    sla: null,
    financial_impact: { amount: 194000, currency: "INR", confidence: 0.79 },
    formula: "idle_driver_minutes * blended_driver_cost_per_minute * recurring_shift_days",
    recommended_action: { label: "Shift riders to evening flex pool and compress low-density shifts", playbook_id: "rider_shift_compress" },
    approval_chain: [
      { step: 1, role: "Scheduling Lead", name: "Sandeep Kulkarni", state: "pending" },
    ],
    timeline: [
      { at: "2026-03-29T14:12:00+05:30", event: "Idle capacity detector triggered", actor: "SLA.ck" },
      { at: "2026-03-29T17:10:00+05:30", event: "Run-rate estimate prepared", actor: "Megha Iyer" },
    ],
  },
};

export const demoLiveOps: LiveWorkItem[] = [
  {
    id: "WI-OPS-1022",
    item_type: "late_delivery_cluster",
    title: "Bengaluru HSR dispatch queue spike",
    team: "Regional Fleet Control",
    owner_name: "Siddharth Rao",
    status: "open",
    current_stage: "monitoring",
    assigned_sla_name: "Customer delivery recovery",
    response_deadline: "2026-03-29T19:08:00+05:30",
    resolution_deadline: "2026-03-29T20:00:00+05:30",
    time_remaining_minutes: 43,
    predicted_breach_risk: "critical",
    projected_penalty: 452000,
    projected_business_impact: 190000,
    linked_case_id: "CASE-SLA-442",
    suggested_action: "Shift 8 riders from BLR-JPN-02 and cap slot density for 45 minutes",
    match_rationale: ["54 delayed orders in 90 minutes", "Dispatch bays at 96% utilization", "Low spare rider coverage nearby"],
    workflow_category: "delivery_exception",
  },
  {
    id: "WI-OPS-1049",
    item_type: "cold_chain_breach",
    title: "Mumbai Andheri chilled-order breach risk",
    team: "Cold Chain Operations",
    owner_name: "Pooja Nair",
    status: "open",
    current_stage: "escalation",
    assigned_sla_name: "Cold chain incident response",
    response_deadline: "2026-03-29T19:12:00+05:30",
    resolution_deadline: "2026-03-29T20:25:00+05:30",
    time_remaining_minutes: 68,
    predicted_breach_risk: "high",
    projected_penalty: 318000,
    projected_business_impact: 122000,
    linked_case_id: "CASE-SLA-517",
    suggested_action: "Reroute chilled orders and dispatch backup reefer unit",
    match_rationale: ["Reefer downtime > 18 min", "Open cold-chain queue above threshold", "Resolution window now under 70 min"],
    workflow_category: "cold_chain_exception",
  },
  {
    id: "WI-OPS-1074",
    item_type: "driver_shortfall",
    title: "Gurgaon driver shortfall building next-slot backlog",
    team: "Regional Fleet Control",
    owner_name: "Arjun Khanna",
    status: "open",
    current_stage: "monitoring",
    assigned_sla_name: "Fleet capacity recovery",
    response_deadline: "2026-03-29T19:24:00+05:30",
    resolution_deadline: "2026-03-29T20:40:00+05:30",
    time_remaining_minutes: 52,
    predicted_breach_risk: "high",
    projected_penalty: 141000,
    projected_business_impact: 88000,
    linked_case_id: "CASE-OPS-305",
    suggested_action: "Trigger standby rider pool and reduce promise window by 3 minutes",
    match_rationale: ["Acceptance rate fell below 72%", "Open exception queue rising into next slot"],
    workflow_category: "staffing_gap",
  },
  {
    id: "WI-OPS-1082",
    item_type: "picker_queue_spike",
    title: "Hyderabad picker queue running above target",
    team: "Dark Store Operations",
    owner_name: "Riya Patel",
    status: "open",
    current_stage: "monitoring",
    assigned_sla_name: "Fulfillment throughput recovery",
    response_deadline: "2026-03-29T19:32:00+05:30",
    resolution_deadline: "2026-03-29T20:52:00+05:30",
    time_remaining_minutes: 84,
    predicted_breach_risk: "medium",
    projected_penalty: 76000,
    projected_business_impact: 54000,
    linked_case_id: null,
    suggested_action: "Move two inventory handlers to picking for the evening spike",
    match_rationale: ["Picker queue 28% above plan", "Bay capacity still available"],
    workflow_category: "fulfillment_delay",
  },
];

export const demoActions: ActionRequest[] = [
  {
    id: "ACT-201",
    case_id: "CASE-INV-118",
    title: "Hold disputed RapidFleet line items",
    recommended_next_step: "Block payment release and issue vendor dispute note",
    rationale: "Rate variance is repeated, material, and not explained by contract addenda.",
    expected_savings: 684000,
    avoided_loss: 180000,
    risk_level: "high",
    required_approver: "Rohit Menon",
    evidence_pack_summary: ["2 repeated invoice cycles", "12.6% rate drift", "No matching contract surcharge"],
    approval_state: "pending",
    execution_state: "drafted",
    created_at: "2026-03-29T18:18:00+05:30",
    updated_at: "2026-03-29T18:20:00+05:30",
  },
  {
    id: "ACT-202",
    case_id: "CASE-SLA-442",
    title: "Rebalance riders into Bengaluru HSR",
    recommended_next_step: "Move surplus riders and temporarily cap slot density",
    rationale: "Dispatch bottleneck is immediate and current delay trajectory will miss SLA.",
    expected_savings: 0,
    avoided_loss: 452000,
    risk_level: "high",
    required_approver: "Pooja Nair",
    evidence_pack_summary: ["54 delayed orders", "96% bay utilization", "43 min response window left"],
    approval_state: "approved",
    execution_state: "queued",
    created_at: "2026-03-29T17:52:00+05:30",
    updated_at: "2026-03-29T18:28:00+05:30",
  },
  {
    id: "ACT-203",
    case_id: "CASE-RES-211",
    title: "Compress Hyderabad low-density rider shifts",
    recommended_next_step: "Move six riders into flex pool and compress afternoon coverage",
    rationale: "Idle capacity is recurring and the run-rate cost is material enough to intervene.",
    expected_savings: 194000,
    avoided_loss: 0,
    risk_level: "medium",
    required_approver: "Sandeep Kulkarni",
    evidence_pack_summary: ["58 idle driver minutes", "72% bay utilization", "Demand 31% below peers"],
    approval_state: "pending",
    execution_state: "drafted",
    created_at: "2026-03-29T17:10:00+05:30",
    updated_at: "2026-03-29T18:11:00+05:30",
  },
  {
    id: "ACT-204",
    case_id: "CASE-OPS-305",
    title: "Trigger Gurgaon standby rider pool",
    recommended_next_step: "Activate reserve rider roster for next two slots",
    rationale: "Driver acceptance is below threshold and backlog is compounding.",
    expected_savings: 0,
    avoided_loss: 141000,
    risk_level: "high",
    required_approver: "Pooja Nair",
    evidence_pack_summary: ["Acceptance rate under 72%", "Queue growth into next slot"],
    approval_state: "approved",
    execution_state: "executed",
    created_at: "2026-03-29T18:01:00+05:30",
    updated_at: "2026-03-29T18:34:00+05:30",
  },
];

export const demoAutoMode: AutoModeSettings = {
  organization_id: 101,
  policies: [
    {
      id: 1,
      name: "Auto-run low-severity invoice holds",
      module: "procurewatch",
      scope: "finance_ap",
      risk_level: "low",
      enabled: true,
      approver_name: "Rohit Menon",
      allowed_actions: ["draft_dispute_note", "hold_line_item"],
      condition_summary: "Only for projected impact below 75k INR and repeat-confidence above 90%.",
      expires_at: null,
    },
    {
      id: 2,
      name: "Auto-escalate cold-chain incidents",
      module: "sla_sentinel",
      scope: "cold_chain",
      risk_level: "high",
      enabled: true,
      approver_name: "Pooja Nair",
      allowed_actions: ["notify_ops", "reroute_orders"],
      condition_summary: "Escalate immediately when chilled-order queue and reefer downtime thresholds are both crossed.",
      expires_at: null,
    },
    {
      id: 3,
      name: "Auto-suggest rider shift compression",
      module: "procurewatch",
      scope: "resource_optimization",
      risk_level: "medium",
      enabled: false,
      approver_name: "Sandeep Kulkarni",
      allowed_actions: ["draft_schedule_change"],
      condition_summary: "Keep in suggestion mode until three consecutive low-density windows are observed.",
      expires_at: null,
    },
  ],
};

export const demoSlaRules: SlaRulebookEntry[] = [
  {
    id: "SLA-101",
    name: "Customer delivery recovery",
    status: "active",
    applies_to: "Late-delivery clusters in metro dark stores",
    applies_to_payload: { label: "Late-delivery clusters in metro dark stores", category: "delivery_exception" },
    conditions: "Trigger when delayed orders exceed 20 in 90 minutes and dispatch bays exceed 90% utilization.",
    response_deadline_hours: 1,
    resolution_deadline_hours: 3,
    penalty_amount: 220000,
    escalation_owner: "Regional Fleet Control",
    business_hours_logic: "24x7",
    auto_action_allowed: true,
    source_document_name: "last_mile_sla_addendum_mar26.pdf",
    last_reviewed_at: "2026-03-29T18:10:00+05:30",
  },
  {
    id: "SLA-102",
    name: "Cold chain incident response",
    status: "active",
    applies_to: "Reefer downtime and chilled-order queues",
    applies_to_payload: { label: "Reefer downtime and chilled-order queues", category: "cold_chain_exception" },
    conditions: "Trigger when reefer downtime exceeds 15 minutes or chilled queue exceeds 12 open orders.",
    response_deadline_hours: 1,
    resolution_deadline_hours: 2,
    penalty_amount: 318000,
    escalation_owner: "Cold Chain Operations",
    business_hours_logic: "24x7",
    auto_action_allowed: true,
    source_document_name: "cold_chain_vendor_contract_v4.pdf",
    last_reviewed_at: "2026-03-29T17:42:00+05:30",
  },
  {
    id: "SLA-103",
    name: "Vendor billing dispute acknowledgement",
    status: "active",
    applies_to: "Material AP invoice disputes",
    applies_to_payload: { label: "Material AP invoice disputes", category: "invoice_variance" },
    conditions: "Projected leakage above 100k INR or repeated variance across two invoice cycles.",
    response_deadline_hours: 4,
    resolution_deadline_hours: 48,
    penalty_amount: 180000,
    escalation_owner: "Finance AP Audit",
    business_hours_logic: "business_hours",
    auto_action_allowed: false,
    source_document_name: "finance_ops_playbook_q1.docx",
    last_reviewed_at: "2026-03-29T16:50:00+05:30",
  },
];

export const demoSlaExtractions: SlaExtractionBatch[] = [
  {
    id: "BATCH-201",
    source_document_name: "north_zone_vendor_msa.pdf",
    document_type: "pdf",
    status: "pending_review",
    uploaded_at: "2026-03-29T17:08:00+05:30",
    extraction_source: "gemini_contract_parse",
    run_metadata: { pages: 34, candidates_found: 2, language: "en" },
    candidate_rules: [
      {
        id: 901,
        name: "North zone staffing shortfall response",
        applies_to: "Driver staffing shortfalls",
        applies_to_payload: { label: "Driver staffing shortfalls", category: "staffing_gap" },
        conditions: "Open shortage > 12 riders for 30 minutes.",
        response_deadline_hours: 1,
        resolution_deadline_hours: 4,
        penalty_amount: 95000,
        escalation_owner: "Regional Fleet Control",
        business_hours_logic: "24x7",
        auto_action_allowed: true,
        status: "pending_review",
        confidence_score: 0.91,
      },
      {
        id: 902,
        name: "Overflow dispatch lane recovery",
        applies_to: "Dispatch congestion events",
        applies_to_payload: { label: "Dispatch congestion events", category: "delivery_exception" },
        conditions: "Dispatch bay utilization > 95% for 45 minutes.",
        response_deadline_hours: 1,
        resolution_deadline_hours: 3,
        penalty_amount: 140000,
        escalation_owner: "Dark Store Operations",
        business_hours_logic: "24x7",
        auto_action_allowed: true,
        status: "pending_review",
        confidence_score: 0.88,
      },
    ],
  },
  {
    id: "BATCH-202",
    source_document_name: "finance_controls_appendix.txt",
    document_type: "txt",
    status: "pending_review",
    uploaded_at: "2026-03-29T16:24:00+05:30",
    extraction_source: "gemini_contract_parse",
    run_metadata: { paragraphs: 12, candidates_found: 1, language: "en" },
    candidate_rules: [
      {
        id: 903,
        name: "High-value AP dispute acknowledgement",
        applies_to: "Vendor invoice disputes above 250k INR",
        applies_to_payload: { label: "Vendor invoice disputes above 250k INR", category: "invoice_variance" },
        conditions: "Projected dispute > 250k INR and confidence > 85%.",
        response_deadline_hours: 2,
        resolution_deadline_hours: 24,
        penalty_amount: 120000,
        escalation_owner: "Finance AP Audit",
        business_hours_logic: "business_hours",
        auto_action_allowed: false,
        status: "pending_review",
        confidence_score: 0.93,
      },
    ],
  },
];

export function pickCopilotScenario(question: string): DemoCopilotScenario {
  const q = question.toLowerCase();

  if (q.includes("sla") || q.includes("late") || q.includes("delay")) {
    return {
      summary: "SLA runtime isolated two stores where breach risk is driven by dispatch saturation rather than rider attendance alone.",
      reasoning: [
        "Loading source memory for order, delivery event, and work item joins.",
        "Checking whether delayed orders cluster by store and hour instead of single-driver exceptions.",
        "Matching delay bursts against dispatch bay and active rider capacity snapshots.",
        "Ranking stores by breach likelihood and near-term penalty exposure.",
      ],
      actions: [
        {
          label: "Profile delayed orders by store",
          note: "Find stores with repeated over-promise misses in the last 24 hours.",
          sql: "select store_id, count(*) as delayed_orders, avg(extract(epoch from (delivered_at - created_at))/60 - promised_eta_min) as avg_delay_min from orders where delivered_at is not null and delivered_at >= now() - interval '1 day' and extract(epoch from (delivered_at - created_at))/60 > promised_eta_min + 8 group by 1 order by delayed_orders desc limit 5;",
        },
        {
          label: "Join dispatch capacity",
          note: "Test whether delays line up with constrained dispatch infrastructure.",
          sql: "select i.store_id, avg(i.dispatch_bay_utilization_pct) as bay_util, avg(i.idle_driver_minutes) as idle_driver_minutes from inventory_snapshots i where i.snapshot_date >= current_date - interval '3 day' group by 1 order by bay_util desc;",
        },
      ],
      result: {
        query_label: "SLA breach risk hotspots",
        sql: "select store_id, delayed_orders, projected_penalty_inr, suggested_action from ranked_sla_hotspots order by projected_penalty_inr desc limit 3;",
        explanation: "Bengaluru HSR and Mumbai Andheri are the highest-risk SLA hotspots. The pattern is operational: dispatch bays are saturated, queue depth is rising, and rider supply alone will not clear the backlog.",
        rows: [
          { store_id: "BLR-HSR-04", delayed_orders: 54, projected_penalty_inr: 452000, suggested_action: "Shift 8 riders from BLR-JPN-02 and throttle slot density for 45 minutes" },
          { store_id: "MUM-AND-01", delayed_orders: 39, projected_penalty_inr: 337000, suggested_action: "Open overflow dispatch lane and route bulk baskets to MUM-VRL-02" },
          { store_id: "GGN-SEC54-02", delayed_orders: 21, projected_penalty_inr: 141000, suggested_action: "Trigger standby picker pool and reduce promised ETA by 3 minutes" },
        ],
      },
    };
  }

  if (q.includes("warehouse") || q.includes("driver") || q.includes("resource") || q.includes("utilization")) {
    return {
      summary: "Resource optimization analysis found two stores with excess rider minutes and one store with severe dispatch strain.",
      reasoning: [
        "Reading resource graph and inventory capacity tables from source memory.",
        "Comparing order density against rider idle minutes and dispatch-bay utilization.",
        "Separating true overstaffing from temporary lull caused by rain or demand shocks.",
        "Ranking opportunities by avoidable monthly run-rate cost.",
      ],
      actions: [
        {
          label: "Find idle rider pockets",
          note: "Search for stores with low dispatch pressure but persistently high idle minutes.",
          sql: "select store_id, avg(idle_driver_minutes) as avg_idle_driver_min, avg(dispatch_bay_utilization_pct) as avg_bay_util from inventory_snapshots group by 1 having avg(idle_driver_minutes) > 45 and avg(dispatch_bay_utilization_pct) < 82 order by avg_idle_driver_min desc;",
        },
        {
          label: "Cross-check order density",
          note: "Validate that low utilization is demand-driven, not caused by data gaps.",
          sql: "select store_id, count(*) as order_count, avg(basket_value) as avg_basket_value from orders where created_at >= now() - interval '7 day' group by 1 order by order_count asc;",
        },
      ],
      result: {
        query_label: "Resource optimization opportunities",
        sql: "select store_id, avg_idle_driver_min, avoidable_monthly_cost_inr, recommended_move from resource_opportunity_rank order by avoidable_monthly_cost_inr desc limit 3;",
        explanation: "Hyderabad KPHB and Noida Sector 76 are over-covered on rider supply relative to dispatch demand. Mumbai Andheri has the opposite problem: it needs more dispatch capacity, not more riders.",
        rows: [
          { store_id: "HYD-KPHB-03", avg_idle_driver_min: 58, avoidable_monthly_cost_inr: 146000, recommended_move: "Shift 6 riders into evening flex pool" },
          { store_id: "NCR-NOI-76", avg_idle_driver_min: 49, avoidable_monthly_cost_inr: 97000, recommended_move: "Collapse low-demand afternoon shift" },
          { store_id: "MUM-AND-01", avg_idle_driver_min: 12, avoidable_monthly_cost_inr: 0, recommended_move: "Add dispatch bay capacity instead of rider headcount" },
        ],
      },
    };
  }

  return {
    summary: "Finance and operations signals both point to repeated leakage in last-mile billing and SLA-linked work items.",
    reasoning: [
      "Loading vendor invoices, contract baselines, and saved anomaly SQL from source memory.",
      "Checking whether invoice variance is isolated to one vendor or repeated across contract families.",
      "Matching vendor leakage with live operational exceptions to separate billing drift from real throughput spikes.",
      "Ranking anomalies by financial exposure and readiness for action.",
    ],
    actions: [
      {
        label: "Run invoice drift detector",
        note: "Apply the saved ProcureWatch query over the last two billing cycles.",
        sql: demoAnomalyQueries[0].sql_text,
      },
      {
        label: "Correlate with operations exceptions",
        note: "See if billed surges are backed by higher order volume or just rate inflation.",
        sql: "select v.vendor_id, sum(i.invoice_amount) as billed_inr, count(distinct w.work_item_id) as related_work_items from invoices i left join work_items w on i.vendor_id = w.assigned_team where i.invoice_date >= current_date - interval '45 day' group by 1 order by billed_inr desc limit 5;",
      },
    ],
    result: {
      query_label: "Top anomaly opportunities",
      sql: "select anomaly_name, owner_team, projected_impact_inr, next_action from anomaly_opportunity_rank order by projected_impact_inr desc limit 4;",
      explanation: "The highest-value issues are not random outliers. They line up directly with the saved anomaly queries already configured in SLA.ck, which is why the same patterns surface in the dashboard.",
      rows: [
        { anomaly_name: "RapidFleet contract rate drift", owner_team: "Finance AP Audit", projected_impact_inr: 684000, next_action: "Issue disputed-line hold and request credit note" },
        { anomaly_name: "Bengaluru HSR dispatch saturation", owner_team: "Regional Fleet Control", projected_impact_inr: 452000, next_action: "Rebalance riders and cap slot density" },
        { anomaly_name: "PolarNest cold-chain penalty risk", owner_team: "Cold Chain Operations", projected_impact_inr: 318000, next_action: "Escalate reefer downtime and reroute chilled orders" },
        { anomaly_name: "Hyderabad KPHB rider idle pocket", owner_team: "Last Mile Scheduling", projected_impact_inr: 194000, next_action: "Compress low-density shift coverage" },
      ],
    },
  };
}
